export const transactionDetails = [
  {
    id: 1,
    month: 'Jan',
    date: '01 Jan 2022',
    time: '08.30 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+500',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$450',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$200',
  },
  {
    id: 13,
    month: 'Jan',
    date: '28 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$100',
  },
  {
    id: 14,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 15,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$200',
  },
  {
    id: 1,
    month: 'Jan',
    date: '29 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '-$200',
  },
  {
    id: 1,
    month: 'Jan',
    date: '29 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '-$200',
  },
  {
    id: 1,
    month: 'Jan',
    date: '29 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$200',
  },
  {
    id: 1,
    month: 'Jan',
    date: '29 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$200',
  },
  {
    id: 1,
    month: 'Jan',
    date: '29 Jan 2022',
    time: '08.39 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$100',
  },
  {
    id: 2,
    month: 'Feb',
    date: '20 Feb 2022',
    time: '08.40 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '+$200',
  },
  {
    id: 3,
    month: 'Mar',
    date: '31 Mar 2022',
    time: '08.41 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '-$100',
  },
  {
    id: 4,
    month: 'Apr',
    date: '29 Apr 2022',
    time: '08.42 AM',
    img: require('.././assets/images/transaction_Images/person4.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$100',
  },
  {
    id: 5,
    month: 'May',
    date: '30 May 2022',
    time: '08.43 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '+$200',
  },
  {
    id: 6,
    month: 'Jun',
    date: '29 Jun 2022',
    time: '08.44 AM',
    img: require('.././assets/images/transaction_Images/person1.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$100',
  },
  {
    id: 7,
    month: 'Jul',
    date: '30 July 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$400',
  },
  {
    id: 8,
    month: 'Aug',
    date: '30 Aug 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Bandi',
    moneyTransfered: '+$600',
  },
  {
    id: 9,
    month: 'Sep',
    date: '30 Sep 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person5.jpeg'),
    firstName: 'Sai',
    moneyTransfered: '+$200',
  },
  {
    id: 10,
    month: 'Oct',
    date: '30 Oct 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Bhanu',
    moneyTransfered: '-$400',
  },
  {
    id: 11,
    month: 'Nov',
    date: '30 Nov 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person3.jpeg'),
    firstName: 'Sekhar',
    moneyTransfered: '+$200',
  },
  {
    id: 12,
    month: 'Dec',
    date: '30 Dec 2022',
    time: '08.45 AM',
    img: require('.././assets/images/transaction_Images/person2.jpeg'),
    firstName: 'Reddy',
    moneyTransfered: '-$200',
  },
];

export const months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
